/**
 * Enum for risk levels.
 * @typedef {'high' | 'medium' | 'low' | 'info'} RiskLevel
 */
export type RiskLevel = 'high' | 'medium' | 'low' | 'info'; // Enum for risk levels
/**
 * Enum for confidence levels.
 * @typedef {'high' | 'medium' | 'low' | 'falsepositive'} ConfidenceLevel
 */
export type ConfidenceLevel = 'high' | 'medium' | 'low' | 'falsepositive'; // Enum for confidence levels


/**
 * Allowed template IDs for reports.
 * @typedef {'high-level-report' | 'modern' | 'risk-confidence-html' | 'traditional-html' | 'traditional-html-plus' | 'traditional-json' | 'traditional-json-plus' | 'sarif-json' | 'traditional-md' | 'traditional-pdf' | 'traditional-xml' | 'traditional-xml-plus'} ReportTemplate
 */
export type ReportTemplate =
  | 'high-level-report'
  | 'modern'
  | 'risk-confidence-html'
  | 'traditional-html'
  | 'traditional-html-plus'
  | 'traditional-json'
  | 'traditional-json-plus'
  | 'sarif-json'
  | 'traditional-md'
  | 'traditional-pdf'
  | 'traditional-xml'
  | 'traditional-xml-plus';

/**
 * Allowed theme IDs for reports.
 * @typedef {'console' | 'construction' | 'corporate' | 'marketing' | 'mountain' | 'nature' | 'ocean' | 'plutonium' | 'skyline' | 'technology'} ReportTheme
 */
export type ReportTheme =
  | 'console'
  | 'construction'
  | 'corporate'
  | 'marketing'
  | 'mountain'
  | 'nature'
  | 'ocean'
  | 'plutonium'
  | 'skyline'
  | 'technology';

/**
 * Interface representing a report configuration.
 * @interface IReport
 * @property {ReportTemplate} [template] - The template ID, restricted to specific values.
 * @property {ReportTheme} [theme] - The template theme, restricted to specific values.
 * @property {string} [reportDir] - The directory into which the report will be written.
 * @property {string} [reportFile] - The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]].
 * @property {string} [reportTitle] - The report title.
 * @property {string} [reportDescription] - The report description.
 * @property {boolean} [displayReport] - Display the report when generated, default: false.
 * @property {RiskLevel[]} [risks] - The risks to include in this report, default all.
 * @property {ConfidenceLevel[]} [confidences] - The confidences to include in this report, default all.
 * @property {string[]} [sections] - The template sections to include in this report - see the relevant template, default all.
 * @property {string[]} [sites] - The sites to include in this report, default all.
 */
export interface IReport {
  template?: ReportTemplate; // The template id, restricted to specific values
  theme?: ReportTheme; // The template theme, restricted to specific values
  reportDir?: string; // The directory into which the report will be written
  reportFile?: string; // The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]]
  reportTitle?: string; // The report title
  reportDescription?: string; // The report description
  displayReport?: boolean; // Display the report when generated, default: false
  risks?: RiskLevel[]; // The risks to include in this report, default all
  confidences?: ConfidenceLevel[]; // The confidences to include in this report, default all
  sections?: string[]; // The template sections to include in this report - see the relevant template, default all
  sites?: string[]; // The sites to include in this report, default all
}

/**
 * Class representing a report configuration.
 * @implements {IReport}
 * @example
 * const reportConfig = new Report({
 *   template: 'traditional-html',
 *   theme: 'corporate',
 *   reportDir: '/reports',
 *   reportFile: '{{yyyy-MM-dd}}-ZAP-Report-[[site]]',
 *   reportTitle: 'Weekly Security Report',
 *   reportDescription: 'This is the weekly security report generated by ZAP.',
 *   displayReport: true,
 *   risks: ['high', 'medium'],
 *   confidences: ['high', 'medium', 'low'],
 *   sections: ['alertSummary', 'siteSummary', 'alertsByRisk'],
 *   sites: ['https://example.com', 'https://another-example.com']
 * });
 */
export class Report implements IReport {
  template?: ReportTemplate; // The template id, restricted to specific values
  theme?: ReportTheme; // The template theme, restricted to specific values
  reportDir?: string; // The directory into which the report will be written
  reportFile?: string; // The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]]
  reportTitle?: string; // The report title
  reportDescription?: string; // The report description
  displayReport?: boolean; // Display the report when generated, default: false
  risks?: RiskLevel[]; // The risks to include in this report, default all
  confidences?: ConfidenceLevel[]; // The confidences to include in this report, default all
  sections?: string[]; // The template sections to include in this report - see the relevant template, default all
  sites?: string[]; // The sites to include in this report, default all

  /**
   * Creates an instance of Report.
   * @param {IReport} options - The options to initialize the report configuration.
   * @property {ReportTemplate} [options.template] - The template ID, restricted to specific values.
   * @property {ReportTheme} [options.theme] - The template theme, restricted to specific values.
   * @property {string} [options.reportDir] - The directory into which the report will be written.
   * @property {string} [options.reportFile] - The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]].
   * @property {string} [options.reportTitle] - The report title.
   * @property {string} [options.reportDescription] - The report description.
   * @property {boolean} [options.displayReport] - Display the report when generated, default: false.
   * @property {RiskLevel[]} [options.risks] - The risks to include in this report, default all.
   * @property {ConfidenceLevel[]} [options.confidences] - The confidences to include in this report, default all.
   * @property {string[]} [options.sections] - The template sections to include in this report - see the relevant template, default all.
   * @property {string[]} [options.sites] - The sites to include in this report, default all.
   * @example
   * const reportConfig = new Report({
   *   template: 'traditional-html',
   *   theme: 'corporate',
   *   reportDir: '/reports',
   *   reportFile: '{{yyyy-MM-dd}}-ZAP-Report-[[site]]',
   *   reportTitle: 'Weekly Security Report',
   *   reportDescription: 'This is the weekly security report generated by ZAP.',
   *   displayReport: true,
   *   risks: ['high', 'medium'],
   *   confidences: ['high', 'medium', 'low'],
   *   sections: ['alertSummary', 'siteSummary', 'alertsByRisk'],
   *   sites: ['https://example.com', 'https://another-example.com']
   * });
   */
  constructor(options: IReport) {
    this.template = options.template;
    this.theme = options.theme;
    this.reportDir = options.reportDir;
    this.reportFile = options.reportFile;
    this.reportTitle = options.reportTitle;
    this.reportDescription = options.reportDescription;
    this.displayReport = options.displayReport;
    this.risks = options.risks;
    this.confidences = options.confidences;
    this.sections = options.sections;
    this.sites = options.sites;
  }
}